connect/accounts/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.accounts.forms import CustomPasswordResetForm
from connect.accounts import views


reset_email_template = 'accounts/emails/password_reset_email.html'

urlpatterns = patterns(
    '',
    # Auth
    url(_(r'^login/$'), auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(_(r'^logout/$'), auth_views.logout,
        {
            'next_page': '/',
            'template_name': 'accounts/login.html'
        },
        name='logout'),

    # page where user can request to reset their password
    url(_(r'^password/reset/$'), auth_views.password_reset,
        {'template_name': 'accounts/password_reset.html',
         'post_reset_redirect': '/accounts/password/reset/done/',
         'from_email': settings.EMAIL_HOST_USER,
         'current_app': 'accounts',
         'email_template_name': 'accounts/emails/password_reset_email.html',
         'html_email_template_name': reset_email_template,
         'subject_template_name': 'accounts/emails/password_reset_subject.txt',
         'password_reset_form': CustomPasswordResetForm},
        name="password-reset"),

    # page to confirm that email has been sent
    url(_(r'^password/reset/done/$'), auth_views.password_reset_done,
        {
            'template_name': 'accounts/password_reset_done.html',
            'current_app': 'accounts',
        },
        name="password-reset-done"),


    # page for user to change password (uses token sent in email)
    url(_(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),
        auth_views.password_reset_confirm,
        {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': '/accounts/password/done/',
            'current_app': 'accounts',
        },
        name="password-reset-confirm"),

    # page confirming password has been reset
    url(_(r'^password/reset/complete/$'),
        auth_views.password_reset_complete,
        {'template_name': 'accounts/password_reset_complete.html'},
        name="password-reset-complete"),

    # Request and activate account
    url(_(r'^request-invitation/$'), views.request_invitation,
        name='request-invitation'),
    url(_(r'^request-invitation/done/$'), TemplateView.as_view(
        template_name='accounts/request_invitation_done.html'),
        name='request-invitation-done'),
    url(_(r'^activate/(?P<token>\w+)$'), views.activate_account,
        name='activate-account'),

    # Profile settings
    url(_(r'^profile/$'), views.profile_settings, name='profile-settings'),

    # Account settings
    url(_(r'^update/email/$'), views.update_email, name='update-email'),
    url(_(r'^update/password/$'), views.update_password,
        name='update-password'),
    url(_(r'^close/$'), views.close_account, name='close-account'),
    url(_(r'^close/done/$'),
        TemplateView.as_view(template_name='accounts/close_account_done.html'),
        name='close-account-done'),
)

connect/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.flatpages import urls as flatpages_urls
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from connect.accounts import urls as accounts_urls
from connect.moderation import urls as moderation_urls
from connect.connection import urls as connect_urls
from connect.discover import urls as discover_urls
from connect.discover.views import dashboard


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(_(r'^admin/'), include(admin.site.urls)),
    url(r'^$', dashboard, name='dashboard'),
    url(_(r'^accounts/'), include(accounts_urls, namespace='accounts')),
    url(_(r'^moderation/'), include(moderation_urls, namespace='moderation')),
    url(_(r'^connections/'), include(connect_urls, namespace='connections')),
    url(_(r'^dashboard/'), include(discover_urls, namespace='discover')),
    url(_(r'^pages/'), include(flatpages_urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connect/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.forms.formsets import formset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.timezone import now
from django.utils.translation import ugettext as _

from connect.utils import send_connect_email

from connect.accounts.forms import (
    ActivateAccountForm, BaseLinkFormSet, BaseSkillFormSet, CloseAccountForm,
    LinkForm, ProfileForm, RequestInvitationForm, SkillForm, UpdateEmailForm,
    UpdatePasswordForm
)
from connect.accounts.models import Role, Skill, UserLink, UserSkill

from connect.accounts.utils import create_inactive_user
from connect.accounts.view_utils import (
    match_link_to_brand, save_links, save_skills
)


User = get_user_model()


def request_invitation(request):
    """
    Allow a member of the public to request an account invitation.
    """
    site = get_current_site(request)

    if request.method == 'POST':
        form = RequestInvitationForm(request.POST, request=request)

        if form.is_valid():

            # Create inactive user
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            new_user = create_inactive_user(email, full_name)

            # Add additional details
            comments = form.cleaned_data['comments']
            new_user.registration_method = new_user.REQUESTED
            new_user.applied_datetime = now()
            new_user.application_comments = comments
            new_user.save()

            # Send email(s) to moderator(s) alerting them of new
            # account application
            moderators = User.objects.filter(is_moderator=True, is_active=True)

            url = request.build_absolute_uri(reverse(
                'moderation:review-applications'))

            subject = _('New account request at {}'.format(site.name))
            template = (
                'moderation/emails/notify_moderators_of_new_application.html'
            )

            for moderator in moderators:
                send_connect_email(subject=subject,
                                   template=template,
                                   recipient=moderator,
                                   site=site,
                                   url=url)

            return redirect('accounts:request-invitation-done')
    else:
        form = RequestInvitationForm(request=request)

    context = {
        'form': form,
    }

    return render(request, 'accounts/request_invitation.html', context)


def activate_account(request, token):
    """
    Allow a user to activate their account with the token sent to them
    by email.
    """
    user = get_object_or_404(User, auth_token=token)

    if not user.auth_token_is_used:
        if request.POST:
            form = ActivateAccountForm(request.POST, user=user)

            if form.is_valid():

                # Activate the user's account
                user.full_name = form.cleaned_data['full_name']
                user.password = make_password(form.cleaned_data['password'])
                user.is_active = True

                user.activated_datetime = now()
                user.auth_token_is_used = True
                user.save()

                email = user.email
                password = request.POST['password']
                user = authenticate(username=email, password=password)
                login(request, user)

                # Redirect to dashboard with welcome message
                request.session['show_welcome'] = True
                return redirect(reverse('dashboard'))

        else:
            form = ActivateAccountForm(user=user)

        context = {
            'user': user,
            'form': form,
        }

    else:
        token_is_used = True

        context = {
            'token_is_used': token_is_used,
        }

    return render(request, 'accounts/activate_account.html', context)


@login_required
def profile_settings(request):
    """
    Allows a user to update their own profile.
    """
    user = request.user

    has_skills = Skill.objects.count() > 0
    has_roles = Role.objects.count() > 0

    SkillFormSet = formset_factory(SkillForm, formset=BaseSkillFormSet)

    user_skills = UserSkill.objects.filter(user=user).order_by('skill__name')
    skill_data = [{'skill': s.skill, 'proficiency': s.proficiency}
                  for s in user_skills]

    LinkFormSet = formset_factory(LinkForm, formset=BaseLinkFormSet)

    user_links = UserLink.objects.filter(user=user).order_by('anchor')
    link_data = [{'anchor': l.anchor, 'url': l.url}
                 for l in user_links]

    if request.method == 'POST':
        form = ProfileForm(request.POST, user=user)
        skill_formset = SkillFormSet(request.POST, prefix='skill')
        link_formset = LinkFormSet(request.POST, prefix='link')

        forms = [form, link_formset]

        if has_skills:
            forms.append(skill_formset)

        if all([f.is_valid() for f in forms]):
            # Save user info
            user.full_name = form.cleaned_data['full_name']
            user.bio = form.cleaned_data['bio']
            user.roles = form.cleaned_data['roles']
            user.save()

            if has_skills:
                save_skills(request, user, skill_formset)

            save_links(request, user, link_formset)

            user_links = UserLink.objects.filter(user=user)
            match_link_to_brand(user_links)

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} profile has been updated.'.format(site.name)))

    else:
        form = ProfileForm(user=user)
        skill_formset = SkillFormSet(initial=skill_data, prefix='skill')
        link_formset = LinkFormSet(initial=link_data, prefix='link')

    context = {
        'form': form,
        'skill_formset': skill_formset,
        'link_formset': link_formset,
        'has_skills': has_skills,
        'has_roles': has_roles,
    }

    return render(request, 'accounts/profile_settings.html', context)


@login_required
def update_email(request):
    """
    Update a user's email
    """
    user = request.user

    if request.method == 'POST':
        form = UpdateEmailForm(request.POST, user=user)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.save()

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} email has been updated.'.format(site.name)))

    else:
        form = UpdateEmailForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/update_email.html', context)


@login_required
def update_password(request):
    """
    Update a user's password
    """
    user = request.user

    if request.method == 'POST':
        form = UpdatePasswordForm(request.POST, user=user)

        if form.is_valid():
            new_pass = make_password(form.cleaned_data['new_password'])
            user.password = new_pass
            user.save()

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} password has been updated.'.format(site.name)))

    else:
        form = UpdatePasswordForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/update_password.html', context)


@login_required
def close_account(request):
    """
    Close a user's account
    """
    user = request.user

    if request.method == 'POST':
        form = CloseAccountForm(request.POST, user=user)

        if form.is_valid():

            user.is_active = False
            user.is_closed = True
            user.save()
            logout(request)

            return redirect(reverse('accounts:close-account-done'))

    else:
        form = CloseAccountForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/close_account.html', context)

connect/accounts/templates/accounts/activate_account.html
{% extends "logged_out.html" %}
{% load i18n %}

{% block page_title %}{% trans "Activate Account" %}{% endblock %}

{% block page_content %}

    {% trans "Activate Account" as title %}

    <div class="container">
        {% if token_is_used %}
            <h3 class="lined">{% trans "Token is Used" %}</h3>
            <p class="intro">
                {% url 'accounts:request-invitation' as url %}
                {% blocktrans trimmed %}
                    We're sorry, this activation token has already been used.  If you already have an account, please login <a href="/">here.</a><br/>
                    To request a new token, please visit the <a href="{{ url }}">request account page</a>.
                {% endblocktrans %}
            </p>

        {% else %}
            <form action="" method="post" class="horizontal-form activate-account" data-parsley-validate>
                {% csrf_token %}
                <fieldset>
                    <legend>{{ title }}</legend>
                    <p class="intro">
                        {% blocktrans with site=request.site.name trimmed %}
                            Activate your {{ site }} account.  If you wish to change the email account you are registered with, you can do so once you have logged in.
                        {% endblocktrans %}
                    </p>
                    <dl>
                        <dt>{% trans "Name" %}</dt>
                        <dd>
                            {{ form.full_name }}
                            {% if form.full_name.errors %}
                                <span class="form-error">
                                    {% for error in form.full_name.errors %}
                                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </dd>
                        <span class="clearfix"></span>
                    </dl>
                    <dl>
                        <dt>{% trans "Password" %}</dt>
                        <dd>
                            {{ form.password }}
                            {% if form.password.errors %}
                                <span class="form-error">
                                    {% for error in form.password.errors %}
                                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </dd>
                        <span class="clearfix"></span>
                    </dl>
                    <dl>
                        <dt>{% trans "Confirm Password" %}</dt>
                        <dd>
                            {{ form.confirm_password }}
                            {% if form.confirm_password.errors %}
                                <span class="form-error">
                                    {% for error in form.confirm_password.errors %}
                                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                    {% endfor %}
                                </span>
                            {% endif %}
                            {% if form.non_field_errors %}
                                <span class="form-error">
                                    {% for error in form.non_field_errors %}
                                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </dd>
                        <span class="clearfix"></span>
                    </dl>
                    <dl>
                        <dt></dt>
                        <dd>
                            <input type="submit" value="{{ title }}" class="button"/>
                        </dd>
                        <span class="clearfix"></span>
                    </dl>
                </fieldset>
            </form>
        {% endif %}
    </div>
{% endblock %}

connect/accounts/templates/accounts/close_account.html
{% extends "accounts/settings_base.html" %}
{% load i18n %}



{% block page_title %}{% trans "Close Account" %}{% endblock %}
{% block close_account_active %}active{% endblock %}

{% block settings_content %}

    {% trans "Close Account" as title %}

    <form action="{% url 'accounts:close-account' %}" method="post" class="horizontal-form close-account" novalidate data-parsley-validate>
        {% csrf_token %}
        <fieldset>
            <legend>{{ title }}</legend>
            <p class="intro">
                {% blocktrans with site=request.site.name trimmed %}
                    Please enter your {{ site }} password to confirm you wish to close your account.
                {% endblocktrans %}
            </p>
            <dl>
                <dt>{% trans "Password" %}</dt>
                <dd>
                    {{ form.password }}
                    {% if form.password.errors %}
                        <span class="form-error">
                            {% for error in form.password.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <dl>
                <dt></dt>
                <dd>
                    <input type="submit" value="{{ title }}" class="button submit"/>
                </dd>
                <span class="clearfix"></span>
            </dl>
        </fieldset>
    </form>
{% endblock %}

connect/accounts/templates/accounts/close_account_done.html
{% extends "logged_out.html" %}
{% load i18n %}

{% block page_title %}{% trans "Account Closed" %}{% endblock %}

{% block page_content %}
    <div class="container">
        <h3 class="lined">{% trans "We're sorry to see you go" %}!</h2>
        <p class="intro">
            {% url 'accounts:request-invitation' as url %}
            {% blocktrans trimmed %}
                Your account has been closed<br/>
                If you would like to reopen your account, please visit the <a href="{{ url }}">request invitation page</a>.
            {% endblocktrans %}
        </p>
    </div>
{% endblock %}

connect/accounts/templates/accounts/login.html
{% extends "logged_out.html" %}
{% load i18n %}

{% block page_title %}{% trans "Login" %}{% endblock %}

{% block messages %}
    {% if form.errors %}
        <p>{% trans "Your email and password didn't match. Please try again." %}</p>
    {% endif %}
{% endblock %}

{% block nav_content %}
    <form method="post" action="{% url 'accounts:login' %}" class="login-form" novalidate>
        {% csrf_token %}
        <div class="pull-left field">
            <label>{% trans "Email" %}</label>
            {{ form.username }}
        </div>

        <div class="pull-left field">
            <label>{% trans "Password" %}</label>
            {{ form.password }}
        </div>

        <div class="pull-left">
            <input type="submit" value="{% trans 'Login' %}" class="button"/>
            <input type="hidden" name="next" value="{{ next }}" />
        </div>
        <div class="clearfix"></div>
        <a class="forgotton" href="{% url 'accounts:password-reset' %}">{% trans "Forgotten your password?" %}</a>
    </form>
{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="content-container">
            <a href="{% url 'accounts:request-invitation' %}" class="button">{% trans "Request an Account" %}</a>
        </div>
    </div>
{% endblock %}

connect/accounts/templates/accounts/password_reset.html
{% extends "logged_out.html" %}
{% load i18n %}

{% block page_title %}{% trans "Retrieve Your Login Details" %}{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="content-container">
            <form action="" method="post" class="horizontal-form" novalidate data-parsley-validate>
                <fieldset>
                    <legend>{% trans "Trouble logging in?" %}</legend>
                    <p class="intro">{% trans "Please enter your email address below, and we will email you instructions for setting a new password" %}.</p>

                    {% csrf_token %}
                    <dl>
                        <dt>{% trans "Email Address" %}</dt>
                        <dd>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <span class="form-error">
                                    {% for error in form.email.errors %}
                                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </dd>
                        <span class="clearfix"></span>
                    </dl>
                    <dl>
                        <dt></dt>
                        <dd>
                            <input type="submit" value="{% trans 'Retrieve Login Details' %}" class="button submit"/>
                        </dd>
                    </dl>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

connect/accounts/templates/accounts/password_reset_confirm.html
{% extends "logged_out.html" %}
{% load i18n %}

{% block page_title %}{% trans "Reset Password" %}{% endblock %}

{% block page_content %}

    {% trans "Reset Password" as title %}

    {% if validlink %}
        <div class="container">
            <div class="content-container">
                <form action="" method="post" class="horizontal-form" id="reset-pass" data-parsley-validate>
                    <fieldset>
                        <legend>{{ title }}</legend>
                        <p class="intro">{% trans "Please enter your new password twice for verification purposes" %}.</p>
                        {% csrf_token %}
                        <dl>
                            <dt>{% trans "New Password" %}</dt>
                            <dd>
                                {{ form.new_password1 }}
                                {% if form.new_password1.errors %}
                                    <span class="form-error">
                                        {% for error in form.new_password1.errors %}
                                            <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                        {% endfor %}
                                    </span>
                                {% endif %}
                            </dd>
                            <span class="clearfix"></span>
                        </dl>
                        <dl>
                            <dt>{% trans "Confirm Password" %}</dt>
                            <dd>
                                {{ form.new_password2 }}
                                {% if form.new_password2.errors %}
                                    <span class="form-error">
                                        {% for error in form.new_password2.errors %}
                                            <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                        {% endfor %}
                                    </span>
                                {% endif %}
                                {% if form.non_field_errors %}
                                    <span class="form-error">
                                        {% for error in form.non_field_errors %}
                                            <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                        {% endfor %}
                                    </span>
                                {% endif %}
                            </dd>
                            <span class="clearfix"></span>
                        </dl>
                        <dl>
                            <dt></dt>
                            <dd>
                                <input type="submit" value="{{ title }}" class="button"/>
                            </dd>
                            <span class="clearfix"></span>
                        </dl>
                    </fieldset>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="content-container">
                <h3 class="lined">{% trans "Invalid Link" %}</h3>
                <p class="intro">{% trans "This password reset link is invalid, possibly because it has already been used" %}.</p>
                <a class="button" href="{% url 'accounts:password-reset' %}">{% trans "Request a New Password Reset" %}</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

connect/accounts/templates/accounts/settings_base.html
{% extends "logged_in.html" %}
{% load i18n %}

{% block myaccount_active %}active{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="four columns alpha">
            <ul class="sidebar-menu">
                <li><a href="{% url 'accounts:profile-settings' %}" class="{% block profile_active %}{% endblock %}">{% trans "Profile Settings" %}</a></li>
                <li><a href="{% url 'accounts:update-email' %}" class="{% block update_email_active %}{% endblock %}">{% trans "Update Email" %}</a></li>
                <li><a href="{% url 'accounts:update-password' %}" class="{% block update_password_active %}{% endblock %}">{% trans "Update Password" %}</a></li>
                <li><a href="{% url 'accounts:close-account' %}" class="{% block close_account_active %}{% endblock %}">{% trans "Close Account" %}</a></li>
            </ul>
        </div>
        <div class="twelve columns omega">
            {% block settings_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

connect/accounts/templates/accounts/update_email.html
{% extends "accounts/settings_base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Update Email" %}{% endblock %}

{% block update_email_active %}active{% endblock %}

{% block settings_content %}

    {% include "messages.html" %}

    <form action="{% url 'accounts:update-email' %}" method="post" class="horizontal-form update-email" novalidate data-parsley-validate>
        {% csrf_token %}
        <fieldset>
            <legend>{% trans "Update Email Address" %}</legend>
            <p class="intro">
                {% blocktrans with site=request.site.name trimmed %}
                    Update your email address here.  This address is used for logging into {{ site }}, as well as when when another user sends you a message.  This information is not displayed on your profile.
                {% endblocktrans %}
            </p>
            <dl>
                <dt>{% trans "Email" %}</dt>
                <dd>
                    {{ form.email }}
                    {% if form.email.errors %}
                        <span class="form-error">
                            {% for error in form.email.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <p class="intro indented">{% trans "Please confirm you wish to update your email address by entering your password." %}</p>
            <dl>
                <dt>{% trans "Password" %}</dt>
                <dd>
                    {{ form.password }}
                    {% if form.password.errors %}
                        <span class="form-error">
                            {% for error in form.password.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <dl>
                <dt></dt>
                <dd>
                    <input type="submit" value="{% trans 'Update Email' %}" class="button submit"/>
                </dd>
                <span class="clearfix"></span>
            </dl>
        </fieldset>
    </form>
{% endblock %}

connect/accounts/templates/accounts/update_password.html
{% extends "accounts/settings_base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Update Password" %}{% endblock %}
{% block update_password_active %}active{% endblock %}

{% block settings_content %}

    {% trans "Update Password" as title %}
    {% include "messages.html" %}

    <form action="{% url 'accounts:update-password' %}" method="post" class="horizontal-form update-password" novalidate data-parsley-validate>
        {% csrf_token %}
        <fieldset>
            <legend>{{ title }}</legend>
            <dl class="update-pass">
                <dt>{% trans "New Password" %}</dt>
                <dd>
                    {{ form.new_password }}
                    {% if form.new_password.errors %}
                        <span class="form-error">
                            {% for error in form.new_password.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <p class="intro indented">{% trans "Please confirm you wish to update your password by entering your current password." %}</p>
            <dl>
                <dt>{% trans "Current Password" %}</dt>
                <dd>
                    {{ form.current_password }}
                    {% if form.current_password.errors %}
                        <span class="form-error">
                            {% for error in form.current_password.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <dl>
                <dt></dt>
                <dd>
                    <input type="submit" value="{{ title }}" class="button"/>
                </dd>
                <span class="clearfix"></span>
            </dl>
        </fieldset>
    </form>
{% endblock %}