connect/moderation/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.moderation import views

urlpatterns = patterns(
    '',
    url(r'^$', views.moderation_home, name='moderators'),
    url(_(r'^invite-user/$'), views.invite_user, name='invite-user'),
    url(_(r'^reinvite-user/$'), views.reinvite_user, name='reinvite-user'),
    url(_(r'^revoke-invitation/$'), views.revoke_invitation,
        name='revoke-invitation'),
    url(_(r'^review-applications/$'), views.review_applications,
        name='review-applications'),
    url(_(r'^review-abuse-reports/$'), views.review_abuse,
        name='review-abuse'),
    url(_(r'^logs/$'), views.view_logs, name='logs'),
    url(_(r'^(?P<user_id>\d+)/report-abuse/$'), views.report_abuse,
        name='report-abuse'),
    url(_(r'^abuse-report-logged/$'), TemplateView.as_view(
        template_name='moderation/abuse_report_logged.html'),
        name='abuse-report-logged'),
)

connect/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.flatpages import urls as flatpages_urls
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from connect.accounts import urls as accounts_urls
from connect.moderation import urls as moderation_urls
from connect.connection import urls as connect_urls
from connect.discover import urls as discover_urls
from connect.discover.views import dashboard


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(_(r'^admin/'), include(admin.site.urls)),
    url(r'^$', dashboard, name='dashboard'),
    url(_(r'^accounts/'), include(accounts_urls, namespace='accounts')),
    url(_(r'^moderation/'), include(moderation_urls, namespace='moderation')),
    url(_(r'^connections/'), include(connect_urls, namespace='connections')),
    url(_(r'^dashboard/'), include(discover_urls, namespace='discover')),
    url(_(r'^pages/'), include(flatpages_urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connect/moderation/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import truncatewords
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


User = settings.AUTH_USER_MODEL


class ModerationLogMsg(models.Model):
    """
    Log a moderation event, e.g. when a new user is invited, approved, etc.
    Or when an abuse report is dealt with
    """
    INVITATION = 'INVITATION'
    REINVITATION = 'REINVITATION'
    APPROVAL = 'APPROVAL'
    REJECTION = 'REJECTION'
    DISMISSAL = 'DISMISSAL'
    WARNING = 'WARNING'
    BANNING = 'BANNING'

    MSG_TYPE_CHOICES = [
        (INVITATION, _('Invitation')),
        (REINVITATION, _('Invitation Resent')),
        (APPROVAL, _('Application Approved')),
        (REJECTION, _('Application Rejected')),
        (DISMISSAL, _('Abuse Report Dismissed')),
        (WARNING, _('Official Warning')),
        (BANNING, _('Ban User')),
    ]

    msg_datetime = models.DateTimeField(_('date and time recorded'),
                                        default=timezone.now)
    msg_type = models.CharField(_('message type'), max_length=20,
                                choices=MSG_TYPE_CHOICES)
    comment = models.TextField(_('log comment'))
    pertains_to = models.ForeignKey(User, verbose_name=_('pertains to'),
                                    related_name='log_messages_about',
                                    help_text=_('User who moderation '
                                                'log is about'))
    logged_by = models.ForeignKey(User, verbose_name=_('logged by'),
                                  related_name='log_messages_by',
                                  help_text=_('Moderator who created the log'))

    class Meta:
        verbose_name = _('log entry')
        verbose_name_plural = _('log entries')

    def __str__(self):
        return '{}: {}'.format(self.get_msg_type_display(),
                               truncatewords(self.comment, 20))

connect/moderation/forms.py
from datetime import date
from parsley.decorators import parsleyfy

from django import forms
from django.contrib.auth import get_user_model
from django.http import Http404
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404

from connect.moderation.models import ModerationLogMsg
from connect.accounts.models import AbuseReport
from connect.accounts.forms import validate_email_availability


User = get_user_model()


@parsleyfy
class InviteMemberForm(forms.Form):
    """
    Form for moderator to invite a new member.
    """
    full_name = forms.CharField(
        max_length=100,
        error_messages={
            'required': _('Please enter a full name.')
        })

    email = forms.EmailField(
        error_messages={
            'required': _('Please enter an email address.'),
            'invalid': _('Please enter a valid email address.')
        })

    def clean(self):
        """
        Make sure email is not already in the system.
        """
        cleaned_data = super(InviteMemberForm, self).clean()
        email = cleaned_data.get('email')
        validate_email_availability(email)

        return cleaned_data


@parsleyfy
class ReInviteMemberForm(forms.Form):
    """
    Form for moderators to reinvite new users.
    Asks moderator to confirm they have sent the email to the correct address.
    """
    def __init__(self, *args, **kwargs):
        self.logged_in_moderator = kwargs.pop('moderator', None)
        super(ReInviteMemberForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(
        error_messages={
            'required': _('Please enter an email address.'),
            'invalid': _('Please enter a valid email address.')
        })

    user_id = forms.IntegerField(widget=forms.HiddenInput)

    def clean(self):
        """
        - Check that the user id is valid.

        - If the moderator changes the email, make sure the new
        email is not already in the system.
        """
        cleaned_data = super(ReInviteMemberForm, self).clean()
        email = cleaned_data.get('email')
        user_id = cleaned_data.get('user_id')

        user = get_object_or_404(User, id=user_id)

        if (user.moderator != self.logged_in_moderator or not user.is_invited_pending_activation()):
            raise Http404

        # If this email is not already registered to this user
        if email != user.email:
            validate_email_availability(email)

        return cleaned_data


@parsleyfy
class RevokeInvitationForm(forms.Form):
    """
    Form for moderator to revoke membership invitation.
    Requires moderator to confirm their action.
    """
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    confirm = forms.BooleanField(error_messages={
        'required': _(
            'Please confirm that you wish to revoke this invitation.')
    })


@parsleyfy
class ModerateApplicationForm(forms.Form):
    """
    Form for moderators to approve or reject an account application.
    """
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    decision = forms.ChoiceField(choices=User.MODERATOR_CHOICES[1:],
                                 widget=forms.HiddenInput)
    comments = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': _('Please explain your decision. '
                             'This information will not be sent to the user, '
                             'but will be recorded in the moderation logs.'),
        }), error_messages={
            'required': _('Please explain your decision.'),
        })


@parsleyfy
class ReportAbuseForm(forms.Form):
    """
    Form for a user to report abusive bahaviour of another user.
    """
    comments = forms.CharField(
        widget=forms.Textarea(),
        error_messages={
            'required': _('Please describe your complaint.'),
        })


@parsleyfy
class ModerateAbuseForm(forms.Form):
    """
    Form for a moderator to:
    - Dismiss an abuse report
    - Issue a warning
    - Remove abuser
    """
    report_id = forms.IntegerField(widget=forms.HiddenInput)
    decision = forms.ChoiceField(choices=AbuseReport.ABUSE_REPORT_CHOICES,
                                 widget=forms.HiddenInput)
    comments = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': _('Please explain your decision. '
                             'This information will be sent to both users '
                             'and recorded in the moderation logs.'),
        }),
        error_messages={
            'required': _('Please explain your decision.'),
        })


class FilterLogsForm(forms.Form):
    """
    Form for a moderator to filter moderation logs by date, type and
    who the report has been logged against and logged by.
    """
    ALL = 'ALL'
    TODAY = 'TODAY'
    YESTERDAY = 'YESTERDAY'
    THIS_WEEK = 'THIS_WEEK'
    CUSTOM = 'CUSTOM'

    DATE_CHOICES = (
        (ALL, _('All')),
        (TODAY, _('Today')),
        (YESTERDAY, _('Yesterday')),
        (THIS_WEEK, _('This Week (Last 7 days)')),
        (CUSTOM, _('Custom Date Range')),
    )

    MSG_FILTER_CHOICES = ModerationLogMsg.MSG_TYPE_CHOICES
    MSG_FILTER_CHOICES.insert(0, (ALL, 'All'))

    msg_type = forms.ChoiceField(choices=MSG_FILTER_CHOICES,
                                 required=False)
    period = forms.ChoiceField(choices=DATE_CHOICES)

    start_date = forms.DateTimeField(
        required=False,
        initial=lambda: date.today().replace(
            year=date.today().year - 1),
        input_formats=('%d/%m/%Y',),
        widget=forms.DateInput(
            format='%d/%m/%Y',
            attrs={
                'class': 'start-date',
                'placeholder': _('Start Date'),
                # Disable by default (unless shown)
                'disabled': 'True',
            }))

    end_date = forms.DateTimeField(required=False,
                                   initial=date.today,
                                   input_formats=('%d/%m/%Y',),
                                   widget=forms.DateInput(
                                       format='%d/%m/%Y',
                                       attrs={
                                           'class': 'end-date',
                                           'placeholder': _('End Date'),
                                           # Disable by default (unless shown)
                                           'disabled': 'True',
                                       }))

    def clean(self):
        """
        If 'CUSTOM' is selected, check that both start_date and end_date
        have a value
        """
        cleaned_data = super(FilterLogsForm, self).clean()
        period = cleaned_data.get('period')

        if period == 'CUSTOM':

            start_date = cleaned_data.get('start_date')
            end_date = cleaned_data.get('end_date')

            if not start_date or not end_date:
                raise forms.ValidationError(
                    _('To filter by date, please provide a '
                      'start and end date.'),
                    code='missing_date')

        return cleaned_data

connect/moderation/templates/moderation/abuse_report_logged.html
{% extends "logged_in.html" %}
{% load i18n %}

{% block page_title %}{% trans "Abuse Report Logged" %}{% endblock %}

{% block page_content %}
    <div class="container">
        <h3 class="lined">{% trans "Your Abuse Report has been logged" %}</h4>
        <p class="intro">
            {% trans "A moderator will review your report and make a decision to either dismiss the report, warn the offender, or ban the offender from their account" %}.<br/>
            {% trans "In all cases, you will be notified by email regarding the outcome" %}.
        </p>
    </div>
{% endblock %}

connect/moderation/templates/moderation/invite_member.html
{% extends "moderation/moderators_base.html" %}
{% load humanize i18n static %}

{% block page_title %}{% trans "Invite a New Member" %}{% endblock %}
{% block invite_member_active %}active{% endblock %}

{% block moderators_content %}

    {% include "messages.html" %}
    {% if reinvitation_form.non_field_errors %}
        <span class="form-error">
            {% for error in reinvitation_form.non_field_errors %}
                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
            {% endfor %}
        </span>
    {% endif %}

    <form action="{% url 'moderation:invite-user' %}" method="post" class="horizontal-form" novalidate data-parsley-validate>
        <fieldset>
            <legend>{% trans "Invite a New Member" %}</legend>
            <p class="intro">{% trans "Please provide the details of the member you wish to invite.  Once they have accepted your invitatation, they will be able to edit the details provided here." %}</p>
            {% csrf_token %}
            {{ invitation_form.form_type }}
            <dl>
                <dt>{% trans "Name" %}</dt>
                <dd>
                    {{ invitation_form.full_name }}
                    {% if invitation_form.full_name.errors %}
                        <span class="form-error">
                            {% for error in invitation_form.full_name.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <dl>
                <dt>{% trans "Email" %}</dt>
                <dd>
                    {{ invitation_form.email }}
                    {% if invitation_form.email.errors %}
                        <span class="form-error">
                            {% for error in invitation_form.email.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                    {% if invitation_form.non_field_errors %}
                        <span class="form-error">
                            {% for error in invitation_form.non_field_errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </dd>
                <span class="clearfix"></span>
            </dl>
            <dl>
                <dt></dt>
                <dd>
                    <input type="submit" value="{% trans 'Invite New Member' %}" class="button"/>
                </dd>
                <span class="clearfix"></span>
            </dl>
        </fieldset>
    </form>
    {% if pending %}
        <h3 class="lined">{% trans "Invitations pending activation" %}</h3>
        <p class="intro">
            {% blocktrans count c=pending|length with count=pending|length|apnumber|title trimmed %}
                {{ count }} member you have invited has not yet activated their account:
            {% plural %}
                {{ count }} members you have invited have not yet activated their account:
            {% endblocktrans %}
        </p>
        <table class="responsive invitation-table">
            <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Email Address" %}</th>
                    <th>{% trans "Date Invited" %}</th>
                    <th class="actions">{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for user in pending %}
                <tr>
                    <td>{{ user.get_full_name|title }}</td>
                    <td class="email"><span class="wrap">{{ user.email }}</span></td>
                    <td class="date">{{ user.date_joined|date:"M d, Y" }}</td>
                    <td class="actions">
                        <a href="#" class="table-link resend-link" data-user="{{ user.id }}" data-email="{{ user.email }}">{% trans "Resend Invitation" %}</a>
                        <a href="#" class="table-link revoke-link last" data-user="{{ user.id }}" data-name="{{ user.get_full_name|title }}" data-email="{{ user.email }}">{% trans "Revoke Invitation" %}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="dialog" id="reinvite-member-dialog" title="{% trans 'Resend Invitation' %}">
            <form action="{% url 'moderation:reinvite-user' %}" method="post" class="reinvite-member-form" data-parsley-validate>
                {% csrf_token %}
                <div class="modal-form-group">
                    <label><strong>{% trans "Email:" %}</strong></label>
                    {{ reinvitation_form.email }}
                </div>
                {{ reinvitation_form.user_id }}
                <input type="submit" value="{% trans 'Resend Invitation' %}" class="button"/>
            </form>
        </div>

        <div class="dialog" id="revoke-member-dialog" title="{% trans 'Revoke Invitation' %}">
            <form action="{% url 'moderation:revoke-invitation' %}" method="post" class="revoke-invitation-form" data-parsley-validate>
                {% csrf_token %}
                <div class="modal-form-group">
                    <label class="revoke-label">
                        {{ revocation_form.confirm }}
                        {% blocktrans trimmed %}
                            Revoke my invitation to <span class="name">this user</span> at <span class="email">this email address</span>.
                        {% endblocktrans %}
                    </label>
                    <p class="intro">{% trans "This action will also remove logs related to inviting this user" %}.</p>
                </div>

                {{ revocation_form.user_id }}
                <input type="submit" value="{% trans 'Revoke Invitation' %}" class="button" />
            </form>
        </div>
    {% endif %}
{% endblock %}

connect/moderation/templates/moderation/logs.html
{% extends "moderation/moderators_base.html" %}
{% load i18n %}

{% block page_title %}{% trans "View Logs" %}{% endblock %}
{% block logs_active %}active{% endblock %}

{% block moderators_content %}
    <h3 class="lined">{% trans "View Logs" %}</h3>

    <form action="" method="get" class="filter-logs">
        <div class="filter-input first">
            <label for="id_msg_type">{% trans "Log Type" %}</label>
            {{ form.msg_type }}
        </div>
        <div class="filter-input">
            <label for="id_period">{% trans "Period" %}</label>
            {{ form.period }}
        </div>
        <span class="clear-me"></span>
        <div class="custom-date">
            <div class="filter-input">
                <label for="id_start_date">Start Date</label>
                {{ form.start_date }}
            </div>
            <div class="filter-input last">
                <label for="id_end_date">End Date</label>
                {{ form.end_date }}
            </div>
        </div>
        {% if form.non_field_errors %}
            <div>
                <span class="form-error">
                    {% for error in form.non_field_errors %}
                        <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                    {% endfor %}
                </span>
            </div>
        {% endif %}
        <div class="clearfix"></div>
        <input type="submit" class="button filter-submit" value="{% trans 'Filter Logs' %}" />
    </form>
    {% if logs %}
        <table class="responsive logs-table">
            <thead>
                <tr>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th>{% trans "Comment" %}</th>
                    <th>{% trans "Logged against (user)" %}</th>
                    <th class="logged-by">{% trans "Logged by (moderator)" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                    <tr>
                        <td class="date">
                            {{ log.msg_datetime|date:"M d, Y" }}
                        </td>
                        <td class="type">{{ log.get_msg_type_display }}</td>
                        <td class="comments">
                            <span class="desktop">
                                {{ log.comment|linebreaksbr|truncatewords_html:20 }}
                                {% if log.comment|wordcount > 21 %}
                                    <a class="read-more" href="#" data-id="{{ log.id }}">{% trans "Read More" %}</a>
                                {% endif %}
                            </span>
                            <span class="mobile">
                                {{ log.comment|linebreaksbr }}
                            </span>
                        </td>
                        <td>{{ log.pertains_to.get_full_name|title }}</td>
                        <td class="logged-by">{{ log.logged_by.get_full_name|title }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="intro">{% trans "Sorry there are no moderation events of this type logged in the system." %}</p>
    {% endif %}

    {% for log in logs %}
        {% if log.comment|wordcount > 21 %}
            <div class="comments-dialog dialog" id="dialog{{ log.id }}" title="{% trans 'Comments for' %} {{ log.get_msg_type_display }} {% trans 'Log from' %} {{ log.msg_datetime|date:'M d, Y' }}">
                <div class="comments">
                    {{ log.comment|linebreaksbr }}
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endblock %}

connect/moderation/templates/moderation/moderators_base.html
{% extends "logged_in.html" %}
{% load i18n %}

{% block moderators_active %}active{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="four columns alpha">
            <ul class="sidebar-menu">

                <li>
                    <a href="{% url 'moderation:moderators' %}" class="{% block invite_member_active %}{% endblock %}">
                        {% trans "Invite a New Member" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'moderation:review-applications' %}" class="{% block review_member_active %}{% endblock %}">
                        {% trans "Review Membership Applications" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'moderation:review-abuse' %}" class="{% block review_abuse_active %}{% endblock %}">
                        {% trans "Review Abuse Reports" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'moderation:logs' %}" class="{% block logs_active %}{% endblock %}">
                        {% trans "View Logs" %}
                    </a>
                </li>
            </ul>
        </div>

        <div class="twelve columns omega">
            {% block moderators_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

connect/moderation/templates/moderation/report_abuse.html
{% extends "logged_in.html" %}
{% load i18n %}

{% block page_title %}{% trans "Report Abuse" %}{% endblock %}

{% block page_content %}
    <div class="container">
        <form action="" method="post" class="horizontal-form" data-parsley-validate>
            <fieldset>
                <legend>{% trans "Log an abuse report against" %} {{ logged_against.get_full_name|title }}</legend>
                <p class="intro">
                    {% blocktrans with user=logged_against.get_full_name|title site=request.site.name trimmed %}
                        Describe the complaint you wish to make against {{ user }}, providing as much relevant information as you can.<br/>
                        Based on the information provided, a {{ site }} moderator will either dismiss the report, warn the user, or ban the user from their account.
                    {% endblocktrans %}
                </p>

                <p class="intro">
                    {% blocktrans with site=request.site.name trimmed %}
                        If your complaint is about a {{ site }} moderator, they will not notified, nor will they be able to view this report.
                    {% endblocktrans %}
                </p>
                {% csrf_token %}

                <!-- Hidden Fields -->
                {{ form.logged_by }}
                {{ form.logged_against }}

                <dl>
                    <dt>{% trans "Comments" %}</dt>
                    <dd>
                        {{ form.comments }}
                        {% if form.comments.errors %}
                            <span class="form-error">
                                {% for error in form.comments.errors %}
                                    <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                                {% endfor %}
                            </span>
                        {% endif %}
                    </dd>
                    <span class="clearfix"></span>
                </dl>
                <dl>
                    <dt></dt>
                    <dd>
                        <input type="submit" value="{% trans 'Report Abuse' %}" class="button"/>
                    </dd>
                    <span class="clearfix"></span>
                </dl>
            </fieldset>
        </form>
    </div>
{% endblock %}

connect/moderation/templates/moderation/review_applications.html
{% extends "moderation/moderators_base.html" %}
{% load humanize i18n static %}

{% block page_title %}{% trans "Review Membership Applications" %}{% endblock %}
{% block review_member_active %}active{% endblock %}

{% block moderators_content %}

    {% include "messages.html" %}

    <h3 class="lined">{% trans "Review Membership Applications" %}</h3>

    {% if pending %}
        <p class="intro">
            {% blocktrans count c=pending|length with count=pending|length|apnumber trimmed %}
                There is {{ count }} pending member application:
            {% plural %}
                There are {{ count }} pending member applications:
            {% endblocktrans %}
        <table class="responsive review-app-table">
            <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Email Address" %}</th>
                    <th>{% trans "Date Requested" %}</th>
                    <th>{% trans "Application Comments" %}</th>
                    <th class="actions">{% trans "Actions" %}</th>

                </tr>
            </thead>
            <tbody>
                {% for user in pending %}
                <tr>
                    <td>{{ user.get_full_name|title }}</td>
                    <td class="email"><span class="wrap">{{ user.email }}</span></td>
                    <td class="date">{{ user.applied_datetime|date:"M d, Y" }}</td>
                    <td class="comments">
                        <span class="desktop">
                            {{ user.application_comments|linebreaksbr|truncatewords_html:20 }}
                            {% if user.application_comments|wordcount > 21 %}
                                <a class="read-more" href="#" data-id="{{ user.id }}">{% trans "Read More" %}</a>
                            {% endif %}
                        </span>
                        <span class="mobile">
                            {{ user.application_comments|linebreaksbr }}
                        </span>
                    </td>
                    <td class="actions">
                        <a href="#" class="table-link decision-link" data-user="{{ user.id }}" data-decision="APP">{% trans "Approve Application" %}</a>
                        <a href="#" class="table-link decision-link last" data-user="{{ user.id }}" data-decision="REJ">{% trans "Reject Application" %}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="dialog" id="review-application-dialog">
            <form action="" method="post" class="review-application-form" data-parsley-validate>
                {% csrf_token %}
                {{ form.user_id }}
                {{ form.decision }}
                <div class="modal-form-group">
                    <label>{% trans "Comments" %}</label>
                    {{ form.comments }}
                    {% if form.comments.errors %}
                        <span class="form-error">
                            {% for error in form.comments.errors %}
                                <span><i class="fa fa-exclamation-triangle"></i>{{ error|escape }}</span>
                            {% endfor %}
                        </span>
                    {% endif %}
                </div>
                <input type="submit" value="{% trans 'Moderate User Application' %}" class="button" />
            </form>
        </div>
    {% else %}
        <div class="">
            <p class="intro">{% trans "There are currently no pending membership applications in the system." %}</p>
        </div>
    {% endif %}

    {% for user in pending %}
        {% if user.application_comments|wordcount > 21 %}
            <div class="comments-dialog dialog" id="dialog{{ user.id }}" title="{% blocktrans with user=user.get_full_name|title %}Application comments for {{ user }}{% endblocktrans %}">
                <div class="comments">
                    {{ user.application_comments|linebreaksbr }}
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endblock %}