connect/accounts/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.accounts.forms import CustomPasswordResetForm
from connect.accounts import views


reset_email_template = 'accounts/emails/password_reset_email.html'

urlpatterns = patterns(
    '',
    # Auth
    url(_(r'^login/$'), auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(_(r'^logout/$'), auth_views.logout,
        {
            'next_page': '/',
            'template_name': 'accounts/login.html'
        },
        name='logout'),

    # page where user can request to reset their password
    url(_(r'^password/reset/$'), auth_views.password_reset,
        {'template_name': 'accounts/password_reset.html',
         'post_reset_redirect': '/accounts/password/reset/done/',
         'from_email': settings.EMAIL_HOST_USER,
         'current_app': 'accounts',
         'email_template_name': 'accounts/emails/password_reset_email.html',
         'html_email_template_name': reset_email_template,
         'subject_template_name': 'accounts/emails/password_reset_subject.txt',
         'password_reset_form': CustomPasswordResetForm},
        name="password-reset"),

    # page to confirm that email has been sent
    url(_(r'^password/reset/done/$'), auth_views.password_reset_done,
        {
            'template_name': 'accounts/password_reset_done.html',
            'current_app': 'accounts',
        },
        name="password-reset-done"),


    # page for user to change password (uses token sent in email)
    url(_(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),
        auth_views.password_reset_confirm,
        {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': '/accounts/password/done/',
            'current_app': 'accounts',
        },
        name="password-reset-confirm"),

    # page confirming password has been reset
    url(_(r'^password/reset/complete/$'),
        auth_views.password_reset_complete,
        {'template_name': 'accounts/password_reset_complete.html'},
        name="password-reset-complete"),

    # Request and activate account
    url(_(r'^request-invitation/$'), views.request_invitation,
        name='request-invitation'),
    url(_(r'^request-invitation/done/$'), TemplateView.as_view(
        template_name='accounts/request_invitation_done.html'),
        name='request-invitation-done'),
    url(_(r'^activate/(?P<token>\w+)$'), views.activate_account,
        name='activate-account'),

    # Profile settings
    url(_(r'^profile/$'), views.profile_settings, name='profile-settings'),

    # Account settings
    url(_(r'^update/email/$'), views.update_email, name='update-email'),
    url(_(r'^update/password/$'), views.update_password,
        name='update-password'),
    url(_(r'^close/$'), views.close_account, name='close-account'),
    url(_(r'^close/done/$'),
        TemplateView.as_view(template_name='accounts/close_account_done.html'),
        name='close-account-done'),
)

connect/connection/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

from connect.connection import views

urlpatterns = patterns(
    '',
    url(_(r'^connect-with-user/(?P<user_id>\d+)/$'), views.connect_with_user, name='connect-with-user'),
)

connect/discover/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

from connect.discover import views

urlpatterns = patterns(
    '',
    url(_(r'^map/$'), views.member_map, name='map'),
)

connect/moderation/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.moderation import views

urlpatterns = patterns(
    '',
    url(r'^$', views.moderation_home, name='moderators'),
    url(_(r'^invite-user/$'), views.invite_user, name='invite-user'),
    url(_(r'^reinvite-user/$'), views.reinvite_user, name='reinvite-user'),
    url(_(r'^revoke-invitation/$'), views.revoke_invitation,
        name='revoke-invitation'),
    url(_(r'^review-applications/$'), views.review_applications,
        name='review-applications'),
    url(_(r'^review-abuse-reports/$'), views.review_abuse,
        name='review-abuse'),
    url(_(r'^logs/$'), views.view_logs, name='logs'),
    url(_(r'^(?P<user_id>\d+)/report-abuse/$'), views.report_abuse,
        name='report-abuse'),
    url(_(r'^abuse-report-logged/$'), TemplateView.as_view(
        template_name='moderation/abuse_report_logged.html'),
        name='abuse-report-logged'),
)

connect/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.flatpages import urls as flatpages_urls
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from connect.accounts import urls as accounts_urls
from connect.moderation import urls as moderation_urls
from connect.connection import urls as connect_urls
from connect.discover import urls as discover_urls
from connect.discover.views import dashboard


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(_(r'^admin/'), include(admin.site.urls)),
    url(r'^$', dashboard, name='dashboard'),
    url(_(r'^accounts/'), include(accounts_urls, namespace='accounts')),
    url(_(r'^moderation/'), include(moderation_urls, namespace='moderation')),
    url(_(r'^connections/'), include(connect_urls, namespace='connections')),
    url(_(r'^dashboard/'), include(discover_urls, namespace='discover')),
    url(_(r'^pages/'), include(flatpages_urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connect/connection/models.py
# from django.db import models

# Create your models here.

connect/discover/forms.py
from django import forms

from connect.accounts.models import Role, Skill


class FilterMemberForm(forms.Form):
    """
    Form for searching for members by their skills and roles.
    """
    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False)

    roles = forms.ModelMultipleChoiceField(
        queryset=Role.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False)

connect/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.forms.formsets import formset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.timezone import now
from django.utils.translation import ugettext as _

from connect.utils import send_connect_email

from connect.accounts.forms import (
    ActivateAccountForm, BaseLinkFormSet, BaseSkillFormSet, CloseAccountForm,
    LinkForm, ProfileForm, RequestInvitationForm, SkillForm, UpdateEmailForm,
    UpdatePasswordForm
)
from connect.accounts.models import Role, Skill, UserLink, UserSkill

from connect.accounts.utils import create_inactive_user
from connect.accounts.view_utils import (
    match_link_to_brand, save_links, save_skills
)


User = get_user_model()


def request_invitation(request):
    """
    Allow a member of the public to request an account invitation.
    """
    site = get_current_site(request)

    if request.method == 'POST':
        form = RequestInvitationForm(request.POST, request=request)

        if form.is_valid():

            # Create inactive user
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            new_user = create_inactive_user(email, full_name)

            # Add additional details
            comments = form.cleaned_data['comments']
            new_user.registration_method = new_user.REQUESTED
            new_user.applied_datetime = now()
            new_user.application_comments = comments
            new_user.save()

            # Send email(s) to moderator(s) alerting them of new
            # account application
            moderators = User.objects.filter(is_moderator=True, is_active=True)

            url = request.build_absolute_uri(reverse(
                'moderation:review-applications'))

            subject = _('New account request at {}'.format(site.name))
            template = (
                'moderation/emails/notify_moderators_of_new_application.html'
            )

            for moderator in moderators:
                send_connect_email(subject=subject,
                                   template=template,
                                   recipient=moderator,
                                   site=site,
                                   url=url)

            return redirect('accounts:request-invitation-done')
    else:
        form = RequestInvitationForm(request=request)

    context = {
        'form': form,
    }

    return render(request, 'accounts/request_invitation.html', context)


def activate_account(request, token):
    """
    Allow a user to activate their account with the token sent to them
    by email.
    """
    user = get_object_or_404(User, auth_token=token)

    if not user.auth_token_is_used:
        if request.POST:
            form = ActivateAccountForm(request.POST, user=user)

            if form.is_valid():

                # Activate the user's account
                user.full_name = form.cleaned_data['full_name']
                user.password = make_password(form.cleaned_data['password'])
                user.is_active = True

                user.activated_datetime = now()
                user.auth_token_is_used = True
                user.save()

                email = user.email
                password = request.POST['password']
                user = authenticate(username=email, password=password)
                login(request, user)

                # Redirect to dashboard with welcome message
                request.session['show_welcome'] = True
                return redirect(reverse('dashboard'))

        else:
            form = ActivateAccountForm(user=user)

        context = {
            'user': user,
            'form': form,
        }

    else:
        token_is_used = True

        context = {
            'token_is_used': token_is_used,
        }

    return render(request, 'accounts/activate_account.html', context)


@login_required
def profile_settings(request):
    """
    Allows a user to update their own profile.
    """
    user = request.user

    has_skills = Skill.objects.count() > 0
    has_roles = Role.objects.count() > 0

    SkillFormSet = formset_factory(SkillForm, formset=BaseSkillFormSet)

    user_skills = UserSkill.objects.filter(user=user).order_by('skill__name')
    skill_data = [{'skill': s.skill, 'proficiency': s.proficiency}
                  for s in user_skills]

    LinkFormSet = formset_factory(LinkForm, formset=BaseLinkFormSet)

    user_links = UserLink.objects.filter(user=user).order_by('anchor')
    link_data = [{'anchor': l.anchor, 'url': l.url}
                 for l in user_links]

    if request.method == 'POST':
        form = ProfileForm(request.POST, user=user)
        skill_formset = SkillFormSet(request.POST, prefix='skill')
        link_formset = LinkFormSet(request.POST, prefix='link')

        forms = [form, link_formset]

        if has_skills:
            forms.append(skill_formset)

        if all([f.is_valid() for f in forms]):
            # Save user info
            user.full_name = form.cleaned_data['full_name']
            user.bio = form.cleaned_data['bio']
            user.roles = form.cleaned_data['roles']
            user.save()

            if has_skills:
                save_skills(request, user, skill_formset)

            save_links(request, user, link_formset)

            user_links = UserLink.objects.filter(user=user)
            match_link_to_brand(user_links)

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} profile has been updated.'.format(site.name)))

    else:
        form = ProfileForm(user=user)
        skill_formset = SkillFormSet(initial=skill_data, prefix='skill')
        link_formset = LinkFormSet(initial=link_data, prefix='link')

    context = {
        'form': form,
        'skill_formset': skill_formset,
        'link_formset': link_formset,
        'has_skills': has_skills,
        'has_roles': has_roles,
    }

    return render(request, 'accounts/profile_settings.html', context)


@login_required
def update_email(request):
    """
    Update a user's email
    """
    user = request.user

    if request.method == 'POST':
        form = UpdateEmailForm(request.POST, user=user)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.save()

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} email has been updated.'.format(site.name)))

    else:
        form = UpdateEmailForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/update_email.html', context)


@login_required
def update_password(request):
    """
    Update a user's password
    """
    user = request.user

    if request.method == 'POST':
        form = UpdatePasswordForm(request.POST, user=user)

        if form.is_valid():
            new_pass = make_password(form.cleaned_data['new_password'])
            user.password = new_pass
            user.save()

            site = get_current_site(request)
            messages.success(request, _(
                'Your {} password has been updated.'.format(site.name)))

    else:
        form = UpdatePasswordForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/update_password.html', context)


@login_required
def close_account(request):
    """
    Close a user's account
    """
    user = request.user

    if request.method == 'POST':
        form = CloseAccountForm(request.POST, user=user)

        if form.is_valid():

            user.is_active = False
            user.is_closed = True
            user.save()
            logout(request)

            return redirect(reverse('accounts:close-account-done'))

    else:
        form = CloseAccountForm(user=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/close_account.html', context)

connect/connection/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404


User = get_user_model()


@login_required
def connect_with_user(request, user_id):
    other_user = get_object_or_404(User, id=user_id)
    context = {
        'other_user': other_user
    }
    return render(request, 'connection/connect_with_user.html', context)

connect/discover/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from connect.discover.forms import FilterMemberForm

User = get_user_model()


@login_required
def dashboard(request):
    """
    Shows all members as a list - with the capacity to filter by
    member skills and roles.

    Session containing 'show_welcome' displays custom message for our
    user's first visit.
    """
    show_welcome = request.session.get('show_welcome')

    if show_welcome is not None:
        del request.session['show_welcome']

    # Get additional profile data
    user = request.user

    # Display members
    listed_users = User.objects.filter(
        is_active=True
    ).order_by(
        'full_name'
    ).prefetch_related(
        'userskill_set',
        'userskill_set__skill',
        'roles',
        'links',
        'links__icon'
    )

    if request.method == 'GET':
        form = FilterMemberForm(request.GET)
        if form.is_valid():
            skills = form.cleaned_data['skills']
            roles = form.cleaned_data['roles']

            if skills:
                listed_users = listed_users.filter(
                    skill__in=skills
                ).distinct()
            if roles:
                listed_users = listed_users.filter(
                    roles__in=roles
                ).distinct()
    else:
        form = FilterMemberForm()

    context = {
        'logged_in_user': user,
        'listed_users': listed_users,
        'form': form,
        'show_welcome': show_welcome,
    }

    return render(request, 'discover/list.html', context)


@login_required
def member_map(request):
    """
    Shows all members on a world map.
    """
    return render(request, 'discover/map.html')

connect/templates/base.html
{% load flatpages i18n static %}
{% get_flatpages as flatpages %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block page_title %}{% endblock %} | {{ request.site.name }}</title>
        <meta name="viewport" content="width=device-width">

        <link href="//fonts.googleapis.com/css?family=Cantarell:400,400italic,700,700italic|Bree+Serif" rel="stylesheet" type="text/css">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/stylesheets/screen.css' %}">

        {% block extra_css %}{% endblock %}

        <script src="{% static 'js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p>
                {% blocktrans trimmed %}
                    You are using an <strong>outdated</strong> browser. Please <a href='http://browsehappy.com/'>upgrade your browser</a> to improve your experience.
                {% endblocktrans %}
            </p>
        <![endif]-->

        <div class="wrapper">
            <div class="messages">
                <div class="container">
                    {% block messages %}
                    {% endblock %}
                </div>
            </div>

            <header>
                <div class="container header-container">
                    <a href="/" class="pull-left app-title">
                        {% if request.site.config.logo %}
                            <img src="{{ MEDIA_URL }}{{ request.site.config.logo }}" alt="{{ request.site.name }}" title="{{ request.site.name }}" />
                        {% else %}
                            {{ request.site.name }}
                        {% endif %}
                    </a>
                    <div class="pull-right">
                        {% block mobile_nav_btn %}{% endblock %}
                        {% block nav_content %}
                        {% endblock %}
                    </div>
                    <div class="clearfix"></div>
                </div>
            </header>

            {% block content %}{% endblock %}

            <div class="push"></div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">
                    {% blocktrans %}
                        <span>Made with <i class="fa fa-heart"></i> by <a href="https://github.com/nlhkabu">nlh</a> and <a href="https://github.com/nlhkabu/connect/blob/master/AUTHORS.rst">contributors</a>.</span>
                    {% endblocktrans %}
                    <span><a href="https://github.com/nlhkabu/connect">{% trans "Fork me on Github" %}.</a></span>
                </p>
                <p class="pull-right">
                    {% for page in flatpages %}
                        <span><a href="{{ page.url }}">{{ page.title }}</a></span>
                    {% endfor %}
                </p>
                <div class="clearfix"></div>
            </div>
        </footer>

        <!-- Load Extra JS  -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.10.1.min.js' %}"><\/script>')</script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
        <script src="{% static 'js/vendor/jquery.dialogOptions.js' %}"></script>
        <script>
            window.ParsleyConfig = {
              errorsWrapper: '<span class="parsley-form-error"></span>',
              errorTemplate: '<span></span>'
            };
        </script>
        <script src="{% static 'js/vendor/parsley.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        {% block extra_js %}{% endblock %}

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>

connect/templates/logged_in.html
{% extends "base.html" %}
{% load i18n %}

{% block mobile_nav_btn %}
    <a href="#" class="mobile-icon pull-right"><i class="fa fa-bars"></i> {% trans "Menu" %}</a>
{% endblock %}

{% block nav_content %}
    <nav class="main">
        <a href="{% url 'dashboard' %}" class="{% block dashboard_active %}{% endblock %}"><i class="fa fa-home"></i></a>
        {% if perms.accounts.access_moderators_section %}
            <a href="{% url 'moderation:moderators' %}" class="{% block moderators_active %}{% endblock %}">{% trans "Moderators" %}</a>
        {% endif %}
        <a href="{% url 'accounts:profile-settings' %}" class="{% block myaccount_active %}{% endblock %}">{% trans "My Account" %}</a>
        <a href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a>
    </nav>
    <div class="clearfix"></div>
{% endblock %}

{% block content %}
    <div class="connect-banner">
        <div class="container">
            <div>
                <h1 class="site-name">{{ request.site.name }}</h1>
                {% if request.site.config.tagline %}
                    <h2>{{ request.site.config.tagline }}</h2>
                {% endif %}
            </div>
            {% block tabs %}{% endblock %}
        </div>
    </div>

    <div class="page-content">
        <div class="content-container">
            {% block page_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

connect/templates/logged_out.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="content-container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

connect/templates/messages.html
{% if messages %}
    <div class="notification-messages">
        {% for message in messages %}
            <p>
                {% if message.tags %}
                    <i class="fa
                        {% if message.tags == 'debug' %}
                            fa-bug
                        {% elif message.tags == 'info' %}
                            fa-info
                        {% elif message.tags == 'success' %}
                            fa-check-square-o
                        {% elif message.tags == 'warning' %}
                            fa-frown-o
                        {% elif message.tags == 'error' %}
                            fa-exclamation-triangle
                        {% endif %}
                    "></i>
                {% endif %}
                {{ message }}
            </p>
        {% endfor %}
    </div>
{% endif %}