connect/accounts/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.accounts.forms import CustomPasswordResetForm
from connect.accounts import views


reset_email_template = 'accounts/emails/password_reset_email.html'

urlpatterns = patterns(
    '',
    # Auth
    url(_(r'^login/$'), auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(_(r'^logout/$'), auth_views.logout,
        {
            'next_page': '/',
            'template_name': 'accounts/login.html'
        },
        name='logout'),

    # page where user can request to reset their password
    url(_(r'^password/reset/$'), auth_views.password_reset,
        {'template_name': 'accounts/password_reset.html',
         'post_reset_redirect': '/accounts/password/reset/done/',
         'from_email': settings.EMAIL_HOST_USER,
         'current_app': 'accounts',
         'email_template_name': 'accounts/emails/password_reset_email.html',
         'html_email_template_name': reset_email_template,
         'subject_template_name': 'accounts/emails/password_reset_subject.txt',
         'password_reset_form': CustomPasswordResetForm},
        name="password-reset"),

    # page to confirm that email has been sent
    url(_(r'^password/reset/done/$'), auth_views.password_reset_done,
        {
            'template_name': 'accounts/password_reset_done.html',
            'current_app': 'accounts',
        },
        name="password-reset-done"),


    # page for user to change password (uses token sent in email)
    url(_(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),
        auth_views.password_reset_confirm,
        {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': '/accounts/password/done/',
            'current_app': 'accounts',
        },
        name="password-reset-confirm"),

    # page confirming password has been reset
    url(_(r'^password/reset/complete/$'),
        auth_views.password_reset_complete,
        {'template_name': 'accounts/password_reset_complete.html'},
        name="password-reset-complete"),

    # Request and activate account
    url(_(r'^request-invitation/$'), views.request_invitation,
        name='request-invitation'),
    url(_(r'^request-invitation/done/$'), TemplateView.as_view(
        template_name='accounts/request_invitation_done.html'),
        name='request-invitation-done'),
    url(_(r'^activate/(?P<token>\w+)$'), views.activate_account,
        name='activate-account'),

    # Profile settings
    url(_(r'^profile/$'), views.profile_settings, name='profile-settings'),

    # Account settings
    url(_(r'^update/email/$'), views.update_email, name='update-email'),
    url(_(r'^update/password/$'), views.update_password,
        name='update-password'),
    url(_(r'^close/$'), views.close_account, name='close-account'),
    url(_(r'^close/done/$'),
        TemplateView.as_view(template_name='accounts/close_account_done.html'),
        name='close-account-done'),
)

connect/connection/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

from connect.connection import views

urlpatterns = patterns(
    '',
    url(_(r'^connect-with-user/(?P<user_id>\d+)/$'), views.connect_with_user, name='connect-with-user'),
)

connect/discover/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

from connect.discover import views

urlpatterns = patterns(
    '',
    url(_(r'^map/$'), views.member_map, name='map'),
)

connect/moderation/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _

from connect.moderation import views

urlpatterns = patterns(
    '',
    url(r'^$', views.moderation_home, name='moderators'),
    url(_(r'^invite-user/$'), views.invite_user, name='invite-user'),
    url(_(r'^reinvite-user/$'), views.reinvite_user, name='reinvite-user'),
    url(_(r'^revoke-invitation/$'), views.revoke_invitation,
        name='revoke-invitation'),
    url(_(r'^review-applications/$'), views.review_applications,
        name='review-applications'),
    url(_(r'^review-abuse-reports/$'), views.review_abuse,
        name='review-abuse'),
    url(_(r'^logs/$'), views.view_logs, name='logs'),
    url(_(r'^(?P<user_id>\d+)/report-abuse/$'), views.report_abuse,
        name='report-abuse'),
    url(_(r'^abuse-report-logged/$'), TemplateView.as_view(
        template_name='moderation/abuse_report_logged.html'),
        name='abuse-report-logged'),
)

connect/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.flatpages import urls as flatpages_urls
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from connect.accounts import urls as accounts_urls
from connect.moderation import urls as moderation_urls
from connect.connection import urls as connect_urls
from connect.discover import urls as discover_urls
from connect.discover.views import dashboard


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(_(r'^admin/'), include(admin.site.urls)),
    url(r'^$', dashboard, name='dashboard'),
    url(_(r'^accounts/'), include(accounts_urls, namespace='accounts')),
    url(_(r'^moderation/'), include(moderation_urls, namespace='moderation')),
    url(_(r'^connections/'), include(connect_urls, namespace='connections')),
    url(_(r'^dashboard/'), include(discover_urls, namespace='discover')),
    url(_(r'^pages/'), include(flatpages_urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connect/discover/forms.py
from django import forms

from connect.accounts.models import Role, Skill


class FilterMemberForm(forms.Form):
    """
    Form for searching for members by their skills and roles.
    """
    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False)

    roles = forms.ModelMultipleChoiceField(
        queryset=Role.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False)

connect/discover/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from connect.discover.forms import FilterMemberForm

User = get_user_model()


@login_required
def dashboard(request):
    """
    Shows all members as a list - with the capacity to filter by
    member skills and roles.

    Session containing 'show_welcome' displays custom message for our
    user's first visit.
    """
    show_welcome = request.session.get('show_welcome')

    if show_welcome is not None:
        del request.session['show_welcome']

    # Get additional profile data
    user = request.user

    # Display members
    listed_users = User.objects.filter(
        is_active=True
    ).order_by(
        'full_name'
    ).prefetch_related(
        'userskill_set',
        'userskill_set__skill',
        'roles',
        'links',
        'links__icon'
    )

    if request.method == 'GET':
        form = FilterMemberForm(request.GET)
        if form.is_valid():
            skills = form.cleaned_data['skills']
            roles = form.cleaned_data['roles']

            if skills:
                listed_users = listed_users.filter(
                    skill__in=skills
                ).distinct()
            if roles:
                listed_users = listed_users.filter(
                    roles__in=roles
                ).distinct()
    else:
        form = FilterMemberForm()

    context = {
        'logged_in_user': user,
        'listed_users': listed_users,
        'form': form,
        'show_welcome': show_welcome,
    }

    return render(request, 'discover/list.html', context)


@login_required
def member_map(request):
    """
    Shows all members on a world map.
    """
    return render(request, 'discover/map.html')

connect/discover/templates/discover/dashboard.html
{% extends "logged_in.html" %}
{% load gravatar i18n %}

{% block dashboard_active %}active{% endblock %}

{% block tabs %}
    <ul class="dash-tabs">
        <li class="{% block list_active %}{% endblock %}">
            <a href="{% url 'dashboard' %}">
                <i class="fa fa-bars"></i>{% trans "List View" %}
            </a>
        </li>
        <li class="{% block map_active %}{% endblock %}">
            <a href="{% url 'discover:map' %}">
                <i class="fa fa-map-marker"></i>{% trans "Map View" %}
            </a>
        </li>
    </ul>
{% endblock %}

{% block page_content %}{% endblock %}

connect/discover/templates/discover/list.html
{% extends "discover/dashboard.html" %}
{% load gravatar i18n staticfiles %}

{% block page_title %}{% trans "Dashboard" %}{% endblock %}

{% block list_active %}active{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="four columns alpha filter">

            <ul class="sidebar-menu mobile-tab-menu">
                <li class="active">
                    <a href="{% url 'dashboard' %}">
                        <i class="fa fa-bars"></i>
                        {% trans "List View" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'discover:map' %}">
                        <i class="fa fa-map-marker"></i>
                        {% trans "Map View" %}
                    </a>
                </li>
            </ul>

            <form action="" method="get" class="filter-form">
                {% if form.skills %}
                    <fieldset>
                        <legend>{% trans "Skills/Interests" %}</legend>
                        {% for skill in form.skills %}
                            {{ skill }}
                        {% endfor %}
                    </fieldset>
                {% endif %}

                {% if form.roles %}
                    <fieldset>
                        <legend>{% trans "Roles" %}</legend>
                        {% for role in form.roles %}
                            {{ role }}
                        {% endfor %}
                    </fieldset>
                {% endif %}

                <fieldset>
                    <legend>{% trans "Location" %}</legend>
                    <label for="all">
                        <input type="radio" name="locationRadios" id="all" value="all" checked />
                        <span>{% trans "All users" %}</span>
                    </label>
                    <label for="close">
                        <input type="radio" name="locationRadios" id="close" value="close" />
                        <span>{% trans "Close to me" %}</span>
                    </label>

                    <div class="close-to-me">
                        <label class="within">{% trans "Within" %}</label>
                        <input type="number" name="" value="" id="" class="tiny"/>
                        <select class="tiny">
                            <option>km</option>
                            <option>mi</option>
                        </select>
                        <button type="">{% trans "apply" %}</button>
                    </div>
                </fieldset>
                <input type="submit" class="button muted" value="{% trans 'Clear' %}" />
                <input type="submit" class="button" value="{% trans 'Refine Results' %}" />
            </form>
        </div>
        <div class="twelve columns omega">
            {% if listed_users %}
                {% for user in listed_users %}
                    <!-- start card -->
                    <div class="user-card {% if user != logged_in_user %} not-me{% endif %}">
                        <div class="user-card-content">
                            <div class="image">
                                <a href="#" class="user-img toggle-user-expand">
                                    {% gravatar user.email 150 %}
                                </a>
                            </div>

                            <div class="user-details">
                                <h3><a href="#" class="toggle-user-expand">
                                    {{ user.full_name }}
                                </a></h3>
                                <p><i class="fa fa-map-marker"></i> Melbourne, Australia</p> <!-- TODO -->

                                {% if user.roles.all %}
                                    <ul class="roles">
                                    {% for role in user.roles.all %}
                                        <li class="badge">{{ role }}</li>
                                    {% endfor %}
                                    </ul>
                                {% endif %}

                                {% if user.userskill_set.all %}
                                    <ul class="user-skills">
                                        {% for user_skill in user.userskill_set.all %}
                                            <li class="badge badge-grey">{{ user_skill.skill.name }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                                <div class="user-expand">
                                    <div class="padding">
                                        <blockquote>
                                            {{ user.bio|linebreaksbr }}
                                        </blockquote>

                                        {% if user.userskill_set.all %}
                                            <div class="skills-container">
                                                <table class="skills">
                                                    <tbody>
                                                        {% for user_skill in user.userskill_set.all %}
                                                            <tr>
                                                                <td class="skill-name">{{ user_skill.skill.name }}</td>
                                                                <td class="skill-ability">
                                                                <div class="ability" data-value="{{ user_skill.get_proficiency_percentage }}" data-description="{{ user_skill.get_proficiency_display }}"></div></td>
                                                            </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        {% endif %}

                                        {% if user.links.all %}
                                            <ul class="user-links">
                                                {% for link in user.links.all %}
                                                    <li>
                                                        <i class="fa {{ link.get_icon }}"></i>
                                                        <a href="{{ link.url }}">{{ link.anchor }}</a>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="user-card-footer">
                            {% if user != logged_in_user %}
                                <a href="{% url 'moderation:report-abuse' user.id %}" class="report-abuse pull-left">
                                    {% trans "Report Abuse" %}
                                </a>
                            {% endif %}
                            <nav class="pull-right">
                                <a href="#" class="pull-right toggle-user-expand full-profile">{% trans "View Full Profile" %}</a>
                                {% if user != logged_in_user %}
                                    <a href="{% url 'connections:connect-with-user' user.id %}" class="pull-right connect-btn">
                                        {% trans "Connect" %}
                                    </a>
                                {% endif %}
                            </nav>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <!-- end card-->
                {% endfor %}
            {% else %}
                <div class="no-results">
                    <h4>{% trans "Sorry!" %}</h4>
                    <p>{% trans "There are no users matching your selected search.  Please try again." %}</p>
                </div>
            {% endif %}
        </div>
    </div>

    {% if show_welcome %}
        <div class="dialog" id="welcome-dialog" title="Welcome to {{ request.site.name }}">
            <div class="welcome-message">
                <p>
                    {% blocktrans with name=logged_in_user.full_name trimmed %}
                        Hi {{ name }},
                    {% endblocktrans %}
                </p>
                <p>
                    {% url 'accounts:profile-settings' as url %}
                    {% blocktrans with site=request.site.name trimmed %}
                        <strong>Thanks for joining {{ site }}!</strong><br/>
                        To get started, we recommend visiting your <a href="{{ url }}">accounts</a> page.
                        Here you can set your preferences, including what information you wish to share with other {{ site }} members.
                    {% endblocktrans %}
                </p>
                <p>
                    {% blocktrans with site=request.site.name trimmed %}
                        Cheers,<br/>
                        The {{ site }} team
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    {% endif %}
{% endblock %}

connect/discover/templates/discover/map.html
{% extends "discover/dashboard.html" %}
{% load i18n static %}

{% block map_active %}active{% endblock %}

{% block page_content %}
    <div class="container">

        <ul class="sidebar-menu mobile-tab-menu">
            <li>
                <a href="{% url 'dashboard' %}">
                    <i class="fa fa-bars"></i>
                    {% trans "List View" %}
                </a>
            </li>
            <li class="active">
                <a href="{% url 'discover:map' %}">
                    <i class="fa fa-map-marker"></i>
                    {% trans "Map View" %}
                </a>
            </li>
        </ul>

        <div id="map-canvas"></div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
        function initialize() {

            var mapOptions = {
                zoom: 2,
                center: new google.maps.LatLng(0, 0)
            };

            var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

            var myLatlng = new google.maps.LatLng(-25.363882,131.044922);

            var image = "{% static 'img/map-marker.png' %}";

            var contentString =
            '<div class="map-content">'+
                '<img class="pull-left" width="80" height="80" src="https://secure.gravatar.com/avatar/a70bd6b3306add68a33bc9f8605accec.jpg?r=g&s=80&d=mm" />'+
                '<div class="map-heading pull-left">'+
                    '<h2 class="map-name"><a href="">Nicole Harris</a></h2>'+
                    '<p class="map-location">Uluru, Australia</p>'+
                    '<ul class="map-skills">'+
                    '<li><span class="badge">Django</span></li>'+
                    '<li><span class="badge">Web Development</span></li>'+
                    '<li><span class="badge">Design</span></li>'+
                    '</ul>'+
                '</div>'+
                '<div class="clearfix"></div>'+
            '</div>';

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: 'Nicole Harris',
                icon: image
            });

            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker);
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>
{% endblock %}